apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: microservices-ingress-gateway
  namespace: istio-experiments-no-mesh-application
spec:
  gatewayClassName: istio
  listeners:
  - name: all-http-on-80
    hostname: completely.made.up.host.com
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: Same
