apiVersion: v1
kind: Namespace
metadata:
  labels:
    istio.io/dataplane-mode: ambient
    # - - - - - - - - - - - - - - - - - - - - - - - -
    # for gateway-to-waypoiny layer-7 processing:
    # - https://github.com/istio/istio/issues/51214
    # - https://github.com/istio/istio/issues/51214
    # - - - - - - - - - - - - - - - - - - - - - - - -
    istio.io/ingress-use-waypoint: "true"
    istio.io/use-waypoint: fancy-waypoint-proxy
  name: istio-experiments-ambient-mode-application
