apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice
  namespace: istio-experiments-application-with-no-mesh
spec:
  template:
    spec:
      containers:
        - name: application
          env:
            - name: CHARACTERS_TO_APPEND_TO_MESSAGE
              value: " | by A"
            - name: OTHER_MICROSERVICE_ENDPOINT_TO_CALL
              value: http://microservice-b.istio-experiments-application-with-no-mesh.svc.cluster.local/endpoint
