apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-installation
  namespace: istio-experiments-istio-system
spec:
  meshConfig:
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY  # disabling all egress traffic unless explicitly registered
  profile: minimal
  tag: 1.28.2
  values:
    cni:
      cniConfDir: /var/snap/microk8s/current/args/cni-network
      cniBinDir: /var/snap/microk8s/current/opt/cni/bin
      excludeNamespaces:
        - istio-experiments-istio-system
    global:
      istioNamespace: istio-experiments-istio-system
      platform: microk8s
