apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-installation
  namespace: istio-system
spec:
  meshConfig:
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY  # disabling all egress traffic unless explicitly registered
  profile: default
  revision: ...TODO...
  tag: ...TODO...
  values:
    cni:
      cniConfDir: /var/snap/microk8s/current/args/cni-network
      cniBinDir: /var/snap/microk8s/current/opt/cni/bin
    global:
      platform: microk8s
