apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-installation
  namespace: istio-experiments-sidecar-mode-istio-system
spec:
  components:
    ingressGateways:
      - enabled: true
        label:
          istio: fancy-ingress-gateway
        name: fancy-ingress-gateway
        namespace: istio-experiments-sidecar-mode-istio-system
  meshConfig:
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY  # disabling all egress traffic unless explicitly registered
  profile: minimal
  tag: 1.28.2
  values:
    global:
      istioNamespace: istio-experiments-sidecar-mode-istio-system
      platform: microk8s
