apiVersion: telemetry.istio.io/v1
kind: Telemetry
metadata:
  name: namespace-telemerty
  namespace: istio-experiments-application-with-sidecar-mode
spec:
  tracing:
    - randomSamplingPercentage: 100
