apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: microservices
  namespace: istio-experiments-with-sidecar-mode
spec:
  hosts:
    - completely-made-up-url
  http:
    - match:
        - uri:
            prefix: /a
      retries:
        attempts: 3
        perTryTimeout: 5s
      rewrite:
        uri: /endpoint
      route:
        - destination:
            host: microservice-a
      timeout: 3s
    - match:
        - uri:
            prefix: /b
      retries:
        attempts: 3
        perTryTimeout: 5s
      rewrite:
        uri: /endpoint
      retries:
        attempts: 3
        perTryTimeout: 5s
      route:
        - destination:
            host: microservice-b
      timeout: 3s
    - match:
        - uri:
            prefix: /c
      retries:
        attempts: 3
        perTryTimeout: 5s
      rewrite:
        uri: /endpoint
      route:
        - destination:
            host: microservice-c
      timeout: 3s
  gateways:
    - microservices-ingress
