apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-installation
  namespace: istio-experiments-ambient-mode-istio-system
spec:
  meshConfig:
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY  # disabling all egress traffic unless explicitly registered
  profile: ambient
  tag: 1.28.2
  values:
    cni:
      cniBinDir: /opt/cni/bin
      cniConfDir: /etc/cni/net.d
      excludeNamespaces:
        - istio-experiments-ambient-mode-istio-system
    global:
      istioNamespace: istio-experiments-ambient-mode-istio-system
    pilot:
      env:
        PILOT_JWT_ENABLE_REMOTE_JWKS: "envoy"
        PILOT_JWT_PUB_KEY_REFRESH_INTERVAL: 1m
        JWKS_RESOLVER_INSECURE_SKIP_VERIFY: "true"
