apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-installation
  namespace: istio-experiments-sidecar-mode-istio-system
spec:
  meshConfig:
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY  # disabling all egress traffic unless explicitly registered
  profile: default
  tag: 1.28.2
  values:
    global:
      istioNamespace: istio-experiments-sidecar-mode-istio-system
